import { Meta, StoryFn } from '@storybook/react';
import { resolveReference } from '@/utils/lib/resolve-reference';
import Header from '.';
import { ProductSuggestion } from '../search/types';

export default {
  title: 'Organisms/Header',
  component: Header,
} as Meta<typeof Header>;

const Template: StoryFn<typeof Header> = (args) => <Header {...args} />;

const productListImage: ProductSuggestion[] = [
  {
    id: '1',
    sku: 'SKU-110',
    image: '/brake-disk.png',
    name: 'PrecisionStop™ 494 Advanced Brake Pad Set',
    url: '/',
  },
  {
    id: '2',
    sku: 'SKU-111',
    image: '/brake-pad.png',
    name: 'UltraGrip™ 122 Performance Brake Pads',
    url: '/',
  },
  {
    id: '3',
    sku: 'SKU-112',
    image: '/brake-system.png',
    name: 'UltraGrip™ 555 Performance Brake Pads',
    url: '/',
  },
  {
    id: '4',
    sku: 'SKU-113',
    image: '/brake-disk.png',
    name: 'UltraGrip™ 555 Performance Brake Pads',
    url: '/',
  },
  {
    id: '5',
    sku: 'SKU-114',
    name: 'Brake Pad Set, disc brake DELPHI LP20',
    image: '/brake-system.png',
    url: '/',
  },
  {
    id: '6',
    sku: 'SKU-115',
    name: 'Brake disc with caliper, LANA SS46',
    image: '/brake-disk.png',
    url: '/',
  },
  {
    id: '7',
    sku: 'SKU-116',
    image: '/brake-disk.png',
    name: 'PrecisionStop™ 494 Advanced Brake Pad Set',
    url: '/',
  },
  {
    id: '8',
    sku: 'SKU-117',
    image: '/brake-pad.png',
    name: 'UltraGrip™ 122 Performance Brake Pads',
    url: '/',
  },
  {
    id: '9',
    sku: 'SKU-118',
    image: '/brake-system.png',
    name: 'UltraGrip™ 555 Performance Brake Pads',
    url: '/',
  },
  {
    id: '10',
    sku: 'SKU-119',
    image: '/brake-disk.png',
    name: 'UltraGrip™ 555 Performance Brake Pads',
    url: '/',
  },
  {
    id: '11',
    sku: 'SKU-120',
    name: 'Brake Pad Set, disc brake DELPHI LP20',
    image: '/brake-system.png',
    url: '/',
  },
  {
    id: '12',
    sku: 'SKU-121',
    name: 'Brake disc with caliper, LANA SS46',
    image: '/brake-disk.png',
    url: '/',
  },
];

export const Primary = Template.bind({});
Primary.args = {
  variant: 'navigation',
  pageLinks: [
    resolveReference({ type: 'link', link: '/' }, 'Member + Benefits'),
    resolveReference({ type: 'link', link: '/' }, 'Sale'),
    resolveReference({ type: 'link', link: '/' }, 'New items'),
  ],
  myAccountMenu: {
    categoryId: 'my-account',
    name: 'My Account',
    path: '/my-account',
    paths: {},
    descendants: [
      {
        categoryId: 'dashboard',
        name: 'Dashboard',
        path: '/dashboard',
        paths: {},
        descendants: [],
      },
      {
        categoryId: 'orders',
        name: 'Orders',
        path: '/orders',
        paths: {},
        descendants: [],
      },
      {
        categoryId: 'quotes',
        name: 'Quotes',
        path: '/quotes',
        paths: {},
        descendants: [],
      },
      {
        categoryId: 'purchase-lists',
        name: 'Purchase Lists',
        path: '/purchase-lists',
        paths: {},
        descendants: [],
      },
      {
        categoryId: 'settings-and-security',
        name: 'Settings & Security',
        path: '/settings-and-security',
        paths: {},
        descendants: [],
      },
      {
        categoryId: 'addresses',
        name: 'Addresses',
        path: '/addresses',
        paths: {},
        descendants: [],
      },
    ],
  },
  categoryLinks: [
    {
      categoryId: 'ct-1',
      name: 'Category-1',
      path: '/',
      paths: {},
      descendants: [
        { categoryId: ' ct-3-sub-1', name: 'Sub-Category-1', path: '/', paths: {}, descendants: [] },
        { categoryId: ' ct-3-sub-2', name: 'Sub-Category-2', path: '/', paths: {}, descendants: [] },
        { categoryId: ' ct-3-sub-3', name: 'Sub-Category-3', path: '/', paths: {}, descendants: [] },
        { categoryId: ' ct-3-sub-4', name: 'Sub-Category-4', path: '/', paths: {}, descendants: [] },
      ],
    },
    {
      categoryId: 'ct-2',
      name: 'Category-2',
      path: '/',
      paths: {},
      descendants: [{ categoryId: 'ct-2-sub-1', name: 'Sub-Category-1', path: '/', paths: {}, descendants: [] }],
    },
    {
      categoryId: 'ct-3',
      name: 'Category-3',
      path: '/',
      paths: {},
      descendants: [
        { categoryId: 'ct-3-sub-1', name: 'Sub-Category-1', path: '/', paths: {}, descendants: [] },
        { categoryId: 'ct-3-sub-2', name: 'Sub-Category-2', path: '/', paths: {}, descendants: [] },
        { categoryId: 'ct-3-sub-3', name: 'Sub-Category-3', path: '/', paths: {}, descendants: [] },
        { categoryId: 'ct-3-sub-4', name: 'Sub-Category-4', path: '/', paths: {}, descendants: [] },
      ],
    },
  ],
  logo: { src: '/sb-assets/THE B2B STORE.png', width: 1481, height: 84 },
  logoLink: resolveReference({ type: 'link', link: '/' }, 'Logo'),
  accountLink: resolveReference({ type: 'link', link: '/' }, 'Logo'),
  cartItems: 23,
  cartLink: resolveReference({ type: 'link', link: '/' }, 'Logo'),
  businessUnits: [
    { name: 'opt1', value: 'opt1' },
    { name: 'opt2', value: 'opt2' },
    { name: 'opt3', value: 'opt3' },
    { name: 'opt4', value: 'opt4' },
  ],
  stores: [
    { name: 'opt1', value: 'opt1' },
    { name: 'opt2', value: 'opt2' },
    { name: 'opt3', value: 'opt3' },
    { name: 'opt4', value: 'opt4' },
  ],
  quotes: 4,
  searchPlaceholder: 'Search by SKU number, product name or keyword',
  searchSuggestions: productListImage,
  quickOrderProducts: [
    {
      id: '1',
      sku: 'SKU-110',
      name: '001-Oil-filter-A1',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '2',
      sku: 'SKU-111',
      name: '002-Spark-plug-B2',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '3',
      sku: 'SKU-112',
      name: '003-Brake-pad-C3',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '4',
      sku: 'SKU-113',
      name: '004-Air-filter-D4',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '5',
      sku: 'SKU-114',
      name: '005-Headlight-bulb-E5',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '6',
      sku: 'SKU-115',
      name: '006-Headlight-bulb-E6',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '7',
      sku: 'SKU-116',
      name: 'PrecisionStop™ 494 Advanced Brake Pad Set',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
    {
      id: '8',
      sku: 'SKU-117',
      name: 'UltraGrip™ 122 Performance Brake Pads',
      maxQuantity: 33,
      image: '',
      url: '/',
    },
  ],
  csvDownloadLink: '/template.csv',
};
